filebeat.inputs:
  - type: log # 新增 log 輸入，監控 log-server 的日誌
    enabled: true
    paths:
      - /log-server-logs/*.log # log-server 容器內的日誌路徑
    # multiline:
    #   pattern: ^\[\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\]
    #   negate: true
    #   match: after

output.logstash:
  hosts: ["logstash:5044"]
# logging.to_files: true
# logging.files:
#   path: /usr/share/filebeat/logs
#   name: filebeat.log
#   rotateeverybytes: 10485760 # 10MB
#   keepfiles: 7
